[project]
name = "notebook"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.6.0",
    "google-genai>=1.43.0",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
